huiwensushu:huiwensushu.o huiwenshu.o sushu.o
	gcc -o huiwensushu huiwensushu.o huiwenshu.o sushu.o
huiwensushu.o:huiwensushu.c
	gcc -c huiwensushu.c
huiwenshu.o:huiwenshu.c
	gcc -c huiwenshu.c
sushu.o:sushu.c
	gcc -c sushu.c
.PHONY:clean run
clean:
	-rm huiwensushu huiwensushu.o huiwenshu.o sushu.o
run:
	./huiwensushu
